# Generated by Django 4.0.3 on 2023-03-25 20:53

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('tel', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('groupeSanguin', models.CharField(max_length=5, choices=(('لا اعرف', 'لا اعرف'), ('o-', 'o-'), ('o+', 'o+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('B+', 'B+'), ('AB+', 'AB+'), ('A+', 'A+')))),
                ('date_Dernier_Don', models.DateField()),
                ('gender', models.CharField(max_length=30, choices=(('Male', 'Male'), ('Female', 'Female')))),
                ('wilaya', models.CharField(max_length=30, choices=(('الحوض الشرقي', 'الحوض الشرقي'),('الحوض الغربي', 'الحوض الغربي'),
                    ('لعصابة', 'لعصابة'),
                    ('كوركول', 'كوركول'),
                    ('لبراكنة', 'لبراكنة'),
                    ('ترارزة', 'ترارزة'),
                    ('أدرار', 'أدرار'),
                    ('انواذيبو', 'انواذيبو'),
                    ('تكانت', 'تكانت'),
                    ('غيديماغا', 'غيديماغا'),
                    ('تيرس زمور', 'تيرس زمور'),
                    ('إنشيري', 'إنشيري'),
                    ('انواكشوط', 'انواكشوط')))),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('pasword', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rendez_vous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('lieu', models.CharField(max_length=15)),
                ('donneur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.donneur')),
            ],
        ),
    ]
