# Generated by Django 4.0.3 on 2023-03-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneur',
            name='groupeSanguin',
            field=models.CharField(choices=[('لا اعرف', 'لا اعرف'), ('o-', 'o-'), ('o+', 'o+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('B+', 'B+'), ('AB+', 'AB+'), ('A+', 'A+')], max_length=10),
        ),
    ]
