# Generated by Django 4.0.3 on 2023-03-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_donneur_groupesanguin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donneur',
            options={'verbose_name': 'متبرع', 'verbose_name_plural': 'المتبرعون'},
        ),
        migrations.AlterModelOptions(
            name='hopital',
            options={'verbose_name': 'مستشفى', 'verbose_name_plural': 'المستشفيات'},
        ),
        migrations.AlterModelOptions(
            name='rendez_vous',
            options={'verbose_name': 'ميعاد', 'verbose_name_plural': 'المواعيد'},
        ),
        migrations.AlterField(
            model_name='donneur',
            name='date_Dernier_Don',
            field=models.DateField(verbose_name='تاريخ_اخرتبرع'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='gender',
            field=models.CharField(choices=[(' دَكر', 'دَكر'), ('انثى', 'انثى')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='groupeSanguin',
            field=models.CharField(choices=[('لا اعرف', 'لا اعرف'), ('o-', 'o-'), ('o+', 'o+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('B+', 'B+'), ('AB+', 'AB+'), ('A+', 'A+')], max_length=10, verbose_name='زمرةالدم'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='password',
            field=models.CharField(max_length=10, verbose_name='كلمةالسر'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='tel',
            field=models.IntegerField(verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='username',
            field=models.CharField(max_length=20, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='nom',
            field=models.CharField(max_length=20, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='date',
            field=models.DateTimeField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='lieu',
            field=models.CharField(max_length=15, verbose_name='المكان'),
        ),
    ]
