# Generated by Django 4.0.3 on 2023-03-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_login_options_remove_donneur_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donneur',
            old_name='username',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=20, verbose_name=' كلمة السر'),
        ),
    ]
