# Generated by Django 4.0.3 on 2023-04-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_rename_username_donneur_nom_alter_login_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopital',
            name='pasword',
        ),
        migrations.AddField(
            model_name='hopital',
            name='password',
            field=models.CharField(default=1, max_length=10, verbose_name='كلمة السر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donneur',
            name='date_Dernier_Don',
            field=models.DateField(verbose_name='تاريخ اخر تبرع'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='wilaya',
            field=models.CharField(choices=[('الحوض الشرقي', 'الحوض الشرقي'), ('الحوض الغربي', 'الحوض الغربي'), ('لعصابة', 'لعصابة'), ('كوركول', 'كوركول'), ('لبراكنة', 'لبراكنة'), ('ترارزة', 'ترارزة'), ('أدرار', 'أدرار'), ('انواذيبو', 'انواذيبو'), ('تكانت', 'تكانت'), ('غيديماغا', 'غيديماغا'), ('تيرس زمور', 'تيرس زمور'), ('إنشيري', 'إنشيري'), ('انواكشوط', 'انواكشوط')], max_length=30, verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='time',
            field=models.TimeField(verbose_name='الوقت'),
        ),
    ]
