# Generated by Django 4.0.3 on 2023-04-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_donneur_gender_alter_donneur_groupesanguin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSanguin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'لا اعرف'), ('2', 'o-'), ('3', 'o+'), ('4', 'A-'), ('5', 'B-'), ('6', 'AB-'), ('7', 'B+'), ('8', 'AB+'), ('9', 'A+')], max_length=10, verbose_name='الاسم')),
                ('volume', models.CharField(max_length=20, verbose_name='الكمية')),
            ],
            options={
                'verbose_name': 'زمرة الدم',
                'verbose_name_plural': 'زمر الدم',
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(' 1', 'الحوض الشرقي'), (' 2', 'الحوض الغربي'), ('3', 'لعصابة'), ('4', 'كوركول'), ('5', 'لبراكنة'), ('6', 'ترارزة'), ('7', 'أدرار'), ('8', 'انواذيبو'), ('9', 'تكانت'), ('10', 'غيديماغا'), (' 11', 'تيرس زمور'), ('12', 'إنشيري'), ('13', 'انواكشوط')], max_length=30, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': ' الولاية',
                'verbose_name_plural': 'الولايات ',
            },
        ),
        migrations.RemoveField(
            model_name='donneur',
            name='groupeSanguin',
        ),
        migrations.RemoveField(
            model_name='donneur',
            name='wilaya',
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='donneur_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.donneur', verbose_name='المتبرع'),
        ),
    ]
