# Generated by Django 4.0.3 on 2023-04-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_groupsanguin_wilaya_remove_donneur_groupesanguin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wilaya',
        ),
        migrations.RemoveField(
            model_name='groupsanguin',
            name='volume',
        ),
        migrations.AddField(
            model_name='donneur',
            name='groupeSanguin',
            field=models.CharField(choices=[('1', 'لا اعرف'), ('2', 'o-'), ('3', 'o+'), ('4', 'A-'), ('5', 'B-'), ('6', 'AB-'), ('7', 'B+'), ('8', 'AB+'), ('9', 'A+')], default=2, max_length=10, verbose_name='زمرةالدم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donneur',
            name='wilaya',
            field=models.CharField(choices=[(' 1', 'الحوض الشرقي'), (' 2', 'الحوض الغربي'), ('3', 'لعصابة'), ('4', 'كوركول'), ('5', 'لبراكنة'), ('6', 'ترارزة'), ('7', 'أدرار'), ('8', 'انواذيبو'), ('9', 'تكانت'), ('10', 'غيديماغا'), (' 11', 'تيرس زمور'), ('12', 'إنشيري'), ('13', 'انواكشوط')], default=1, max_length=30, verbose_name='الولاية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupsanguin',
            name='name',
            field=models.CharField(choices=[('o-', 'o-'), ('o+', 'o+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('B+', 'B+'), ('AB+', 'AB+'), ('A+', 'A+')], max_length=10, verbose_name='الاسم'),
        ),
    ]
